<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RightMenuCheck.Core\RightMenuCheck.Core.csproj" />
    <ProjectReference Include="..\RightMenuCheck.Probe.Protocol\RightMenuCheck.Probe.Protocol.csproj" />
  </ItemGroup>

</Project>
