<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\RightMenuCheck.App\Assets\RightMenuCheck.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\distribution\update-public-key.pem"
                      Link="update-public-key.pem" />
    <Resource Include="..\RightMenuCheck.App\Assets\RightMenuCheck.ico"
              Link="Assets\RightMenuCheck.ico" />
    <Resource Include="..\RightMenuCheck.App\Assets\RightMenuCheck.png"
              Link="Assets\RightMenuCheck.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RightMenuCheck.Distribution\RightMenuCheck.Distribution.csproj" />
    <ProjectReference Include="..\RightMenuCheck.Windows\RightMenuCheck.Windows.csproj" />
  </ItemGroup>

</Project>
